USE [master]
GO

/****** Object:  Database [FacturadorDB]    Script Date: 6/9/2022 15:16:37 ******/
CREATE DATABASE [FacturadorDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FacturadorDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\FacturadorDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FacturadorDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\FacturadorDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FacturadorDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FacturadorDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FacturadorDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FacturadorDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FacturadorDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FacturadorDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [FacturadorDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [FacturadorDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FacturadorDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FacturadorDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FacturadorDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FacturadorDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FacturadorDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FacturadorDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FacturadorDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FacturadorDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [FacturadorDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FacturadorDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FacturadorDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FacturadorDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FacturadorDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FacturadorDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [FacturadorDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FacturadorDB] SET RECOVERY FULL 
GO

ALTER DATABASE [FacturadorDB] SET  MULTI_USER 
GO

ALTER DATABASE [FacturadorDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FacturadorDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FacturadorDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FacturadorDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [FacturadorDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [FacturadorDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [FacturadorDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [FacturadorDB] SET  READ_WRITE 
GO


